### PR TITLE
fix: navigate back to supplier orders page after finalizing order reconciliation:

### LINKED ISSUE #830: bug: orders: commit reconciliation order doesn't navigate
I feel it should navigate back to supplier orders or something...

### PR DESCRIPTION
**Pull request by ikusteu**
* apply the fix + add e2e test

Fixes #830

### CODE REVIEW

File: apps/web-client/src/routes/orders/suppliers/reconcile/[id]/+page.svelte [hunk 1]
```diff
@@ -43,8 +43,6 @@
 		// Unsubscribe on unmount
 		disposer();
 	});
-	//#endregion reactivity
```
Comment (silviot) [inline apps/web-client/src/routes/orders/suppliers/reconcile/[id]/+page.svelte:46]: The corresponding opening tag on line 32 should be removed as well.

File: apps/e2e/integration/reconciliation_order.spec.ts [hunk 2]
```diff
@@ -1706,3 +1706,48 @@ testOrders("commit: applies delivery updates to customer order lines", async ({
...
+	await dialog.waitFor({ state: "detached" });
+
+	// Should have navigated back to supplier orders
+	//
+	// These buttons should be enough to conclude we're back at the supplier orders page
+	await page.getByRole("button", { name: "Unordered", exact: true }).waitFor();
+	await page.getByRole("button", { name: "Ordered", exact: true }).waitFor();
+	await page.getByRole("button", { name: "Reconciling", exact: true }).waitFor();
+	await page.getByRole("button", { name: "Completed", exact: true }).waitFor();
+});
```
Comment (silviot) [inline apps/e2e/integration/reconciliation_order.spec.ts:1753]: This is the actual "meat" of the test: making sure we're redirected after confirming the reconciliation.

I'm thinking about pros and cons of this approach (a single test is responsible for a single piece of behaviour) vs adding assertions to existing tests.

My instinct goes to keeping the number of tests in check, so I'd prefer having this added as part of the existing three tests.

Two of them state `// Should navigate to supplier orders` and then proceed to click a UI link to navigate to a different page. I think replacing that comment with these checks would have the advantage of not introducing an additional test. And the disadvantage that a single test has too many responsibilities.

**Review by silviot — CHANGES_REQUESTED** [review]

File: apps/e2e/integration/reconciliation_order.spec.ts (hunk 2 above)
Comment (ikusteu) [reply apps/e2e/integration/reconciliation_order.spec.ts]: Right...so, this was done as part of this work (to provide a test for the functionality). It could have been added to an existing test, but the existing tests were under refactor. Afterwards, the refactor came in and became part of `main` (and, by rebase, this branch).
I've moved this assertino to an existing test

**Review by silviot — APPROVED** [review]
