### PR TITLE
Enhance/supplier handlers

### LINKED ISSUE #721: Fix: `upsertSupplier`
Doesn't work when updating existing fields. See commented-out tests in `supplier-publishers.test`

### PR DESCRIPTION
**Pull request by ikusteu**
Some updates to supplier handlers as part of #529 work
Fixes #721

### CODE REVIEW

File: apps/web-client/src/lib/db/cr-sqlite/suppliers.ts [hunk 1]
```diff
@@ -80,20 +135,26 @@ export async function getPublishersFor(db: DB, supplierId: number): Promise<stri
...
+			INSERT INTO supplier_publisher (supplier_id, publisher)
+			VALUES (?, ?)
+			ON CONFLICT(publisher) DO UPDATE SET
+			supplier_id = ?
+		`,
+		[supplierId, publisher, supplierId]
 	);
 }
 
+export async function removePublisherFromSupplier(db: DB, supplierId: number, publisher: string) {
```
Comment (delasous) [inline apps/web-client/src/lib/db/cr-sqlite/suppliers.ts:154]: Add Jsdoc comment

**Review by delasous — APPROVED** [review]
